# verison 1.1
name: CI
on: [push]
jobs:
  test-sanity:
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      REZILION_RUN_REMEDIATE: true
      REZILION_SEVERITY_GATE: "critical"
 
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.7.0 
        with:
          mode: 'start'
          image_name: 'tomblue01/webapp001:latest'
          command: 'sleep 45'
          
      - uses: Rezilion/github-action@v2.7.0 
        with:
          mode: 'start'
          image_name: 'tomblue01/webapp001:latest'
#          command: 'cd /home/webgoat ; timeout 30 java -Duser.home=/home/webgoat -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED -Dwebgoat.host=0.0.0.0 -Dwebwolf.host=0.0.0.0 -Dwebgoat.port=8080 -Dwebwolf.port=9090 -jar webgoat.jar || true'
          command: cd /home/webgoat ; timeout 30 java -Duser.home=/home/webgoat -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED -Dwebgoat.host=0.0.0.0 -Dwebwolf.host=0.0.0.0 -Dwebgoat.port=8080 -Dwebwolf.port=9090 -jar webgoat.jar || true
          command: 'sleep 45'
        
  Rezilion:
    needs: [test-sanity]
    runs-on: ubuntu-latest
    container:
      image: centos:centos7
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      REZILION_RUN_REMEDIATE: true
    steps:
      - uses: actions/checkout@v3
      #- uses: ./.github/actions/Rezilion #example using the private action
      - uses: Rezilion/github-action@v2.7.0
        with:
          mode: 'validate'
              
  
